# Generated by Django 3.2 on 2021-04-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_active_cases', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_active_cases', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_vaccines', models.IntegerField()),
                ('address', models.CharField(max_length=1023)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.districts')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.states')),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('adhaar', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=1023)),
                ('profession', models.CharField(choices=[('medical_worker', 'Medical Worker'), ('teacher', 'Teacher')], max_length=255)),
                ('priority', models.IntegerField()),
                ('vaccination_status', models.CharField(choices=[('unregistered', 'Unregistered'), ('registered_1', 'Registered for Dose 1'), ('registered_2', 'Registered for Dose 2'), ('vaccinated', 'Vaccinated')], max_length=255)),
                ('vaccine_1_time', models.DateTimeField()),
                ('vaccine_2_time', models.DateTimeField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.districts')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.states')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_vaccines', models.IntegerField()),
                ('address', models.CharField(max_length=1023)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.districts')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.states')),
            ],
        ),
        migrations.AddField(
            model_name='districts',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.states'),
        ),
    ]
