# Generated by Django 3.2 on 2021-04-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterVaccinationStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_vaccines', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='states',
            name='number_of_people_vaccinated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='states',
            name='number_of_vaccines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='states',
            name='state_code',
            field=models.CharField(choices=[('IN-AN', 'IN-AN'), ('IN-AP', 'IN-AP'), ('IN-AR', 'IN-AR'), ('IN-AS', 'IN-AS'), ('IN-BR', 'IN-BR'), ('IN-CH', 'IN-CH'), ('IN-CT', 'IN-CT'), ('IN-DN', 'IN-DN'), ('IN-DL', 'IN-DL'), ('IN-GA', 'IN-GA'), ('IN-GJ', 'IN-GJ'), ('IN-HR', 'IN-HR'), ('IN-HP', 'IN-HP'), ('IN-JK', 'IN-JK'), ('IN-JH', 'IN-JH'), ('IN-KA', 'IN-KA'), ('IN-KL', 'IN-KL'), ('IN-LA', 'IN-LA'), ('IN-LD', 'IN-LD'), ('IN-MP', 'IN-MP'), ('IN-MH', 'IN-MH'), ('IN-MN', 'IN-MN'), ('IN-ML', 'IN-ML'), ('IN-MZ', 'IN-MZ'), ('IN-NL', 'IN-NL'), ('IN-OR', 'IN-OR'), ('IN-PY', 'IN-PY'), ('IN-PB', 'IN-PB'), ('IN-RJ', 'IN-RJ'), ('IN-SK', 'IN-SK'), ('IN-TN', 'IN-TN'), ('IN-TG', 'IN-TG'), ('IN-TR', 'IN-TR'), ('IN-UP', 'IN-UP'), ('IN-UT', 'IN-UT'), ('IN-WB', 'IN-WB')], default='IN-AN', max_length=10),
        ),
        migrations.AlterField(
            model_name='districts',
            name='number_of_active_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='states',
            name='number_of_active_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='number_of_vaccines',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ManufacturingSite',
        ),
    ]
