# Generated by Django 3.2 on 2021-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20210430_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='vaccination_center_chosen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='population',
            name='vaccination_status',
            field=models.CharField(choices=[('unregistered', 'Unregistered'), ('registered_1', 'Registered for Dose 1'), ('dose_1_administered', 'Dose 1 administered'), ('registered_2', 'Registered for Dose 2'), ('vaccinated', 'Vaccinated')], max_length=255),
        ),
    ]
