# Generated by Django 3.2 on 2021-04-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20210430_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='state_population',
            field=models.IntegerField(default=0),
        ),
    ]
