# Generated by Django 3.2 on 2021-04-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_states_state_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='profession',
            field=models.CharField(choices=[('medical_worker', 'Medical Worker'), ('teacher', 'Teacher'), ('engineer', 'Engineer'), ('student', 'Student')], max_length=255),
        ),
    ]
